# Generated by Django 4.2.5 on 2023-10-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_time_to_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_to_read',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
