# Generated by Django 4.2.5 on 2023-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_to_read',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
